#define PROJ_SCREENMODE MODE_FAST_16COLOR
#define PROJ_FPS 255
#define PROJ_HIGH_RAM HIGH_RAM_ON
#define PROJ_PERSISTENCE true
#define PROJ_ENABLE_SOUND 0
#define PROJ_EXT0_PWM_ENABLE
#define PROJ_AUD_FREQ           22050
#define PROJ_USE_PWM 1
