#define PROJ_SCREENMODE MODE_FAST_16COLOR
//#define PROJ_SCREENMODE MODE_HI_4COLOR
#define PROJ_FPS 60
#define PROJ_HIGH_RAM HIGH_RAM_ON
#define PROJ_PERSISTENCE true
#define PROJ_ENABLE_SOUND 0
//#define PROJ_EXT0_PWM_ENABLE